Diff implementation and action forms
inspirehep/ng2-multi-record-editor pull request #12
Opened 2017-08-09 08:48 UTC by Glignos

2017-08-09 12:35 UTC, zzacharo requested changes

2017-08-09 12:35 UTC, zzacharo commented on src/app/action-template/action-template.component.html
> +      <select name='bla' class="form-control" [(ngModel)]="selectedAction" required>
'bla'?

2017-08-09 12:39 UTC, zzacharo requested changes

2017-08-09 12:39 UTC, zzacharo commented on src/app/actions-template/actions-template.component.ts
> +  increaseAction(){
put a space `increaseAction() {}`

2017-08-09 12:39 UTC, zzacharo commented on src/app/actions-template/actions-template.component.ts
> +  increaseAction(){
refactor according to this style..

2017-08-09 12:39 UTC, zzacharo commented on src/app/multi-editor/multi-editor.component.scss
> +.item-group{
space too..

2017-08-09 12:39 UTC, zzacharo commented on src/app/multi-editor/multi-editor.component.ts
> +import { Component,Input,Output, OnInit, EventEmitter, ElementRef  } from '@angular/core';
space between commas.

2017-08-09 12:39 UTC, zzacharo commented on src/index.html
> +<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
we dont need this cause we use `ng2bootstrap` module.

2017-08-09 12:39 UTC, zzacharo commented on src/styles.css
> + "styles": [
that's why we don't need the link to cdn ;)

2017-08-09 12:44 UTC, harunurhan requested changes
There are quite a few things to look at (code-style and standards mostly), when you address them, I will check the logic/code.

2017-08-09 12:44 UTC, harunurhan commented on src/app/action-template/action-template.component.ts
> +const ACTIONS: string[] = ['Addition','Deletion','Update'];
outside variable is not cool, put in a static class variable if you need to have it.

2017-08-09 12:44 UTC, harunurhan commented on src/app/action-template/action-template.component.ts
> +  constructor() { }
constructor should be after properties

2017-08-09 12:44 UTC, harunurhan commented on src/app/action-template/actions-template.component.ts
> +  actions: object[] = [];
[Optional] prefer `Array<T>` instead of `T[]`

2017-08-09 12:44 UTC, harunurhan commented on src/app/actions-template/actions-template.component.ts
> +
single empty line here.

2017-08-09 12:44 UTC, harunurhan commented on src/app/actions-template/actions-template.component.ts
> +
no new line here.

2017-08-09 12:44 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +    this.keys = this.keys;
what is exactly going on here?

2017-08-09 12:44 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +  req_keys = [];
`camelCase` 😄

2017-08-09 12:44 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +  req_keys = [];
Also more descriptive name would be nice.

2017-08-09 12:44 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +         this.keys = this.keys.concat(subkeys.map(x => {return `${key}->${x}`;}));
don't have to put `{}` and `return` for single line arrow functions.

2017-08-09 12:44 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +    console.log(this.req_keys)
leftover

2017-08-09 12:44 UTC, harunurhan commented on src/app/app.module.ts
> +import { AlertModule } from 'ngx-bootstrap';
`ngx-bootstrap/alert` is better to import from here.

2017-08-09 12:44 UTC, harunurhan commented on src/app/diff-template/diff-template.component.ts
> +  selector: 'diff-template',
don't call a component template, templates have different meaning in angular context, so `diff-view` would be better.

2017-08-09 12:44 UTC, harunurhan commented on src/app/diff-template/diff-template.component.ts
> +  diff_objects;
`camelCase` and type

2017-08-09 12:44 UTC, harunurhan commented on src/app/addition-template/addition-template.component.html
> +<div *ngFor="let key of keys">
doesn't it focus out on inputs here when you type something without `trackBy` on `*ngFor`

2017-08-09 12:44 UTC, harunurhan commented on src/app/diff-template/diff-template.component.html
> +<pre><span *ngFor="let diff of diff_objects" [ngClass]="{added: diff.added, removed: diff.removed}">{{diff.value}}</span><pre>
it's better to avoid one liners in html.

2017-08-09 12:44 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +const COLLECTIONS: string[] = [
no variable is out of the class

2017-08-09 12:44 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +  p: number = 1;
when you assign a value during definition, you don't have to put the type.

2017-08-09 12:44 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +  new_records: object[];
`camelCase`

2017-08-09 12:44 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +    this.new_records=[{
left-over or what?

2017-08-09 12:44 UTC, harunurhan commented on src/app/shared/pipes/diff-pipe.pipe.ts
> +export class DiffPipePipe implements PipeTransform {
`DiffPipe` and the name of the file `diff.pipe.ts`

2017-08-09 12:44 UTC, harunurhan commented on src/app/shared/pipes/diff-pipe.pipe.ts
> +  transform(object1: object, object2: object): any {
return type.

2017-08-09 12:44 UTC, harunurhan commented on src/index.html
> +<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
redundant since you will have it in `angular-cli.json`

2017-08-09 12:44 UTC, harunurhan commented on src/styles.css
> + "styles": [
this is broken.

2017-08-09 12:44 UTC, harunurhan commented on src/styles.css
> + "styles": [
this should be like https://github.com/inspirehep/record-editor/blob/master/angular-cli.json#L22

2017-08-09 12:44 UTC, harunurhan commented on src/styles.css
> + "styles": [
And don't forget to install it https://github.com/inspirehep/record-editor/blob/master/package.json#L52

2017-08-09 12:44 UTC, harunurhan commented on src/styles.css
>  /* You can add global styles to this file, and also import other style files */
this file should also be `.scss`

2017-08-30 09:16 UTC, harunurhan requested changes

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.ts
> +    return this.schemaKeysStoreService.find_subschema(this.action.mainKey)
remove the parameter if you don't use it.

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.ts
> +    this.myRecord = event;
`event` => `record: Object` would be better

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.ts
> +  editor = false;
`shouldShowEditor` or `isEditorVisible` or similar.

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.scss
> +.input_fields {
input-field

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.scss
> +.button {
check bootstrap `.btn`, I think it has some of this then try to extend it instead of rewriting.

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.ts
> +  @Output() onElementDeleted: EventEmitter<any> = new EventEmitter();
not type! and also remove `on` prefix & `d`

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.html
> +      <div *ngIf="editor == true" style="width: 700px; height:300px;"> <json-editor *ngIf="editor == true" [config]="{}" [schema]="getSubschema(mainKey)" [record]="{shittyProperty:{}}" (onRecordChang
no inline `style` in template

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.html
> +      <label>Update Value:</label><label style="margin-left:150px">Regex</label><input style="margin-left:4px;" type="checkbox" [(ngModel)]="action.updateRegex">
ditto

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.html
> +      <label>Where Value:</label><label style="margin-left:150px">Regex</label><input style="margin-left:4px;" type="checkbox" [(ngModel)]="action.whereRegex" >
nope

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.html
> +      <label>Where Value:</label><label style="margin-left:150px">Regex</label><input style="margin-left:4px;" type="checkbox" [(ngModel)]="action.whereRegex">
also this one

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.html
> +      <label>Where Value:</label><label style="margin-left:150px">Regex</label><input style="margin-left:4px;" type="checkbox" [(ngModel)]="action.whereRegex">
we don't like inline

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.html
> +      <label>Where Value:</label><label style="margin-left:150px">Regex</label><input style="margin-left:4px;" type="checkbox" [(ngModel)]="action.whereRegex">
don't use more than 2 elements in a single line

2017-08-30 09:16 UTC, harunurhan commented on src/app/action-template/action-template.component.ts
> +import { Action } from '../actions-template/actions-template.component'
put `index.ts` for to each folder so that you can import/refactor easily.

For instance here,` import { Action } from '../actions-template'`

2017-08-30 09:16 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +  ngOnInit() {
remove

2017-08-30 09:16 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +  map = {};
better name

2017-08-30 09:16 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +  @Input() mainKey;
type!

2017-08-30 09:16 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +  ngOnChanges(changes) {
`: SimpleChanges`

2017-08-30 09:16 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +  ngOnChanges(changes) {
`ngOnChanges` is better to be used more carefully, which means you should check if `changes['yourInputPropertyWhichYouCare']` is defined then do the computation

2017-08-30 09:16 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +import { Component, OnInit, Input } from '@angular/core';
format this file!

2017-08-30 09:16 UTC, harunurhan commented on src/app/diff-view/diff-view.component.ts
> +    if (this.newObject != undefined) {
`if (this.newObject)`

2017-08-30 09:16 UTC, harunurhan commented on src/app/diff-view/diff-view.component.ts
> +  diffObjects;
type!

2017-08-30 09:16 UTC, harunurhan commented on src/app/diff-view/diff-view.component.ts
> +      this.diffObjects = diffJson(JSON.parse(JSON.stringify(this.oldObject)), this.newObject)
why `parse(stringify(`?

2017-08-30 09:16 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +  newRecords: object[];
`Array<Object>`

2017-08-30 09:16 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +    private http: Http) { }
no http in component, `apiService` is for this.

2017-08-30 09:16 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +      this.apiService.fetchUrl(`http://localhost:5000/api/multieditor/search?page_num=1&query_string=''`),
use environments for base url `http://localhost:5000/`

2017-08-30 09:16 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +    return Promise.reject(error.message || error);
returning a promise from catch means that you want to continue chaining, I don't see this is the case here so remove this, actually inline the thing inside catch.

2017-08-30 09:16 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +  private pageChanged($event){
`private` shouldn't be used in template

2017-08-30 09:16 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +  private pageChanged($event){
better name and type for `$event`

2017-08-30 09:16 UTC, harunurhan commented on src/app/shared/services/schema-keys-store.service.ts
>    public separator = '/';
share this separator via service or sth, because it's like everywhere!

2017-08-30 09:16 UTC, harunurhan commented on src/app/shared/services/schema-keys-store.service.ts
> +  public schema;
create a type(interface) for schema

2017-08-30 09:16 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.html
> +        <div style ="margin-left:73%">
no more

2017-08-30 09:16 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.html
> +        <li *ngFor="let record of records ; let count = index " class="list-group list-group-item">
`let i = index` is better

2017-08-30 09:16 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.html
> +                <li role="menuitem"><a class="dropdown-item" href="{{collection}}">{{collection}}</a></li>
`[href]="collection"`

2017-08-30 09:16 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.html
> +                    	<span id="searchConcept">Filter by Collection</span> <span class="caret"></span>
why `id`?

2017-08-30 09:16 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.html
> +          <input type="checkbox" [checked]="(allSelected && checkedRecords.indexOf(record.control_number) === -1) || (allSelected === false && checkedRecords.indexOf(record.control_number)>-1)" (chan
remove `checked` and `change` and use `[(ngModel)]="selectionMap[record.control_number]"`

See the other comment on `ts` file.

2017-08-30 09:16 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +  checkedRecords = [] //records that are different from the general selection rule
make it map where key is `control_number ` and value is `boolean` for selected or not and when all selected/deselected just make everything true/false. It's more clear implementation on template and here.

2017-08-30 09:16 UTC, harunurhan commented on src/app/shared/services/schema-keys-store.service.ts
> +    return {'properties':{shittyProperty:subSchema}, 'type':'object'}
don't need this

2017-09-06 13:18 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +    return Promise.reject(error.message || error);
```
catch((error) => {
 this.errorMessage = error.message;
})
```

2017-10-10 11:26 UTC, closed without merging