Implementation of ng2 multi editor
inspirehep/ng2-multi-record-editor pull request #13
Opened 2017-10-04 12:12 UTC by Glignos

2017-10-04 13:34 UTC, harunurhan requested changes

2017-10-04 13:34 UTC, harunurhan commented on angular-cli.json
> +        "../node_modules/font-awesome/css/font-awesome.css"
before `styles.scss`

2017-10-04 13:34 UTC, harunurhan commented on package.json
> +    "font-awesome": "^4.7.0",
to `dependencies`

2017-10-04 13:34 UTC, harunurhan commented on src/app/action-template/action-template.component.html
> +    <option *ngFor="let actionOption of actionOptions" [ngValue]="actionOption" > {{actionOption}} </option>
`actionOptions` can be hardcoded.

2017-10-04 13:34 UTC, harunurhan commented on src/app/action-template/action-template.component.ts
> +  @Output() elementDeleted: EventEmitter<any> = new EventEmitter();
lose the type and `new EventEmitter<number>()`

2017-10-04 13:34 UTC, harunurhan commented on src/app/actions-template/actions-template.component.ts
> +  //@ViewChildren(ActionTemplateComponent) actionComponents: QueryList<ActionTemplateComponent>;
left over

2017-10-04 13:34 UTC, harunurhan commented on src/app/actions-template/actions-template.component.ts
> +  actions:Action [] = [];
`Action[]` or `Array<Action>`

2017-10-04 13:34 UTC, harunurhan commented on src/app/actions-template/actions-template.component.ts
> +  @Output() onPreview: EventEmitter<Object> = new EventEmitter();
lose the type and `new EventEmitter<Array<Action>>();`

2017-10-04 13:34 UTC, harunurhan commented on src/app/actions-template/actions-template.component.ts
> +    var that = this;
left over

2017-10-04 13:34 UTC, harunurhan commented on src/app/actions-template/actions-template.component.ts
> +    //this.actionComponents.forEach(SubmitInstance => that.actions.push(SubmitInstance.SubmitAction()));
left over

2017-10-04 13:34 UTC, harunurhan commented on src/app/actions-template/actions-template.component.ts
> +  submitActions() {
`previewActions`

2017-10-04 13:34 UTC, harunurhan commented on src/app/addition-template/addition-template.component.html
> +<input *ngIf="isEditorVisible == false" (keyup.enter)="getSubschema(action.mainKey)" type="text" [(ngModel)]="action.mainKey"
(keyup.enter)="onFieldKeyInputEnterKeyup()"

2017-10-04 13:34 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +    return this.subSchema;
no need to return

2017-10-04 13:34 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +  getSubschema() {
change the name (see comment up in the template)

2017-10-04 13:34 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +  checkSchema() {
remove this function and move the thing in the caller function or sth.

2017-10-04 13:34 UTC, harunurhan commented on src/app/addition-template/addition-template.component.html
> +    <json-editor [config]="{compact:true}" [schema]="subSchema" [record]="myRecord" (recordChange)="saveRecord($event)"></json-editor>
use `[(record)]="action.value"` no `(recordChange)` needed.

2017-10-04 13:34 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +  addValue(targetArray:string[]) {
remove the target array __mess__ since you are always calling it for `action.whereValues` and maybe call it `addEmptyWhereValue` or sth

2017-10-04 13:34 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +  identify(index:number){
`trackByFunction` also `return` type.

2017-10-04 13:34 UTC, harunurhan commented on src/app/autocomplete/autocomplete.component.ts
> +  @Input() _tags: Set<string> = Set<string>();
`_` prefixed input not good, also no need for type.

2017-10-04 13:34 UTC, harunurhan commented on src/app/autocomplete/autocomplete.component.ts
> +  @Output() onValueChange: EventEmitter<Array<string>> = new EventEmitter<Array<string>>();
no type needed.

2017-10-04 13:34 UTC, harunurhan commented on src/app/autocomplete/autocomplete.component.ts
> +  dataSource: Observable<any>;
`Observable<string>` or `Array<string>` maybe?

2017-10-04 13:34 UTC, harunurhan commented on src/app/autocomplete/autocomplete.component.ts
> +  get tags(): Set<string> {
unnecessary

2017-10-04 13:34 UTC, harunurhan commented on src/app/autocomplete/autocomplete.component.ts
> +  set tags(tags: Set<string>) {
unnecessary

2017-10-04 13:34 UTC, harunurhan commented on src/app/autocomplete/autocomplete.component.ts
> +    let path = '';
you can use `this.currentPath` directly.

2017-10-04 13:34 UTC, harunurhan commented on src/app/autocomplete/autocomplete.component.ts
> +  get typeaheadNoResults() {
not needed.

2017-10-04 13:34 UTC, harunurhan commented on src/app/autocomplete/autocomplete.component.ts
> +  set typeaheadNoResults(e: boolean) {
not needed

2017-10-04 13:34 UTC, harunurhan commented on src/app/diff-view/diff-view.component.ts
> +  diffObjects: Object[];
use the correct type,(as far as I remember it's `IDiffResult`, you can import from `diff`)

2017-10-04 13:34 UTC, harunurhan commented on src/app/diff-view/diff-view.component.ts
> +  ngOnChanges() {
```
ngOnChanges(changes: SimpleChanges) {
  if (changes['oldObject'] || changes['newObject']) {
....
```

2017-10-04 13:34 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +  error_text: string;
`errorText`

2017-10-04 13:34 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +  @Input() records: Array<{}>;
move `@input` up

2017-10-04 13:34 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +  actionsUsed: Object[];
`object []`

2017-10-04 13:34 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +  checkedRecords = [] //records that are different from the general selection rule
`type`

2017-10-04 13:34 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.html
> +            <select class="form-control selector collection-selector" [ngModel]="selectedCollection" (ngModelChange)="setCollection($event)">
`onCollectionChange($event)`

2017-10-04 13:34 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +  private pageChanged($event) {
`page: number`

2017-10-04 13:34 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +    .then((res) => {
`json`

2017-10-04 13:34 UTC, harunurhan commented on src/app/shared/services/query.service.ts
> +export class QueryService {
put the `baseUrl` here

2017-10-04 13:34 UTC, harunurhan commented on src/app/shared/services/query.service.ts
> +    .post(`${url}/update`, {
for object literal do it,
`{ foo: bar, dude, prop: aVariable}` instead of `{ 'foo': bar, 'dude': dude, 'prop': aVariable}`

2017-10-04 14:20 UTC, Glignos commented on src/app/addition-template/addition-template.component.ts
> +  identify(index:number){
not sure what you mean for the return type

2017-10-05 08:13 UTC, harunurhan commented on src/app/addition-template/addition-template.component.ts
> +  identify(index:number){
`: number`

2017-10-10 07:36 UTC, zzacharo requested changes

2017-10-10 07:36 UTC, zzacharo commented on src/app/action-template/action-template.component.ts
> +  @Output() onActionDeleted: EventEmitter<number> = new EventEmitter();
you can simplify `@Output() onActionDeleted = new EventEmitter<nunber>();`

2017-10-10 07:36 UTC, zzacharo commented on src/app/actions-template/actions-template.component.ts
> +  onActionDeleted(event) {
change `event` parameter to the actual parameter which is `actionIndex` and add type number.

2017-10-10 07:36 UTC, zzacharo commented on src/app/actions-template/actions-template.component.ts
> +  onConditionDeleted(event) {
the same as above.

2017-10-10 07:36 UTC, zzacharo commented on src/app/addition-template/addition-template.component.ts
> +  onFieldKeyInputEnterKeyup() {
simplify it to `onEnterKeyUp()`

2017-10-10 07:36 UTC, zzacharo commented on src/app/conditions-template/conditions-template.component.ts
> +  @Output() onConditionDeleted: EventEmitter<number> = new EventEmitter();
you can simplify it as in a previous comment.

2017-10-10 07:36 UTC, zzacharo commented on src/app/deletion-template/deletion-template.component.ts
> +  reduceValue(targetArray: string[]) {
rename `deleteValue`

2017-10-10 07:36 UTC, zzacharo commented on src/app/diff-view/diff-view.component.scss
> +}
newline

2017-10-10 07:36 UTC, zzacharo commented on src/app/shared/classes/index.ts
> +];
delete this file was a leftover.

2017-10-10 07:36 UTC, zzacharo commented on src/app/shared/classes/node.ts
> +}
delete this too.

2017-10-10 07:36 UTC, zzacharo commented on src/app/shared/index.ts
> +  SHARED_CLASSES
delete `SHARED_CLASSES`

2017-10-10 07:36 UTC, zzacharo commented on src/app/shared/services/api.service.ts
> +  fetchUrl(url: string): Observable<any> {
leave the array type.

2017-10-10 07:36 UTC, zzacharo commented on src/app/shared/services/api.service.ts
> +import { Observable } from 'rxjs/Rx';
try again with the previous import.

2017-10-10 07:36 UTC, zzacharo commented on src/app/shared/services/schema-keys-store.service.ts
> +          .filter(key => this.isObjectOrArraySchema(schema['items']['properties'][key]))
space due to format or mistake?

2017-10-10 07:36 UTC, zzacharo commented on src/app/update-template/update-template.component.ts
> +  reduceValue(targetArray: string[]) {
deleteValue

2017-10-10 07:54 UTC, zzacharo approved these changes

2017-10-10 11:07 UTC, harunurhan approved these changes

2017-10-10 11:27 UTC, merged