autocomplete: Add autocomplete input fields
inspirehep/ng2-multi-record-editor pull request #26
Opened 2017-10-16 09:26 UTC by zzacharo

Signed-off-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>

2017-10-16 14:13 UTC, harunurhan requested changes

2017-10-16 14:13 UTC, harunurhan commented on src/app/autocomplete-input/autocomplete-input.component.html
> +  <i class="fa fa-remove"></i> No Results FoundW
leftover `W`

2017-10-16 14:13 UTC, harunurhan commented on src/app/autocomplete-input/autocomplete-input.component.ts
> +  @Input() styleClass = '';
`className` and no init needed I think

2017-10-16 14:13 UTC, harunurhan commented on src/app/autocomplete-input/autocomplete-input.component.ts
> +  @Output() valueChange: EventEmitter<string> = new EventEmitter<string>();
no type needed

2017-10-16 14:13 UTC, harunurhan commented on src/app/autocomplete-input/autocomplete-input.component.ts
> +  splitToken = '/';
`readonly`, also `private` since not used in component template.

2017-10-16 14:13 UTC, harunurhan commented on src/app/autocomplete-input/autocomplete-input.component.ts
> +  private _typeaheadNoResults = false;
not need to make this `private` and have `set` and `get`

2017-10-16 14:13 UTC, harunurhan commented on src/app/autocomplete-input/autocomplete-input.component.ts
> +    let slashIndex = token.lastIndexOf(this.splitToken);
`separatorIndex`  since we might change it to something else than `slash`

2017-10-16 14:13 UTC, harunurhan commented on src/app/autocomplete-input/autocomplete-input.component.ts
> +  splitToken = '/';
`separator`

2017-10-16 14:13 UTC, harunurhan commented on src/app/autocomplete-input/autocomplete-input.component.ts
> +  getStatesAsObservable(token: string): Observable<any> {
doing all this logic in this method is too much. I suggest you do a `map` before `mergeMap` that takes `token` that returns `path` and `lastSeparatorIndex` then a [do](https://www.learnrxjs.io/operators/utility/do.html)  that assigns the` path` to` currentPath` then another `map` finally returns the `queryRegExp`

After all of this, this function would be only `return` statement.

2017-10-17 06:55 UTC, zzacharo commented
@harunurhan check it again.

2017-10-17 08:04 UTC, harunurhan reviewed
little more as we discussed, just to make code clear

2017-10-17 08:04 UTC, harunurhan commented on src/app/autocomplete-input/autocomplete-input.component.ts
> +    }).do(state => {
`state: {path: string, query: string}`

2017-10-17 08:04 UTC, harunurhan commented on src/app/autocomplete-input/autocomplete-input.component.ts
> +    }).map(state => {
remove

2017-10-17 08:04 UTC, harunurhan commented on src/app/autocomplete-input/autocomplete-input.component.ts
> +        this.schemaKeysStoreService.forPath(state['path']).filter(item => state['query'].test(item))
`item.startsWith(query)`

2017-10-17 08:04 UTC, harunurhan commented on src/app/autocomplete-input/autocomplete-input.component.ts
> +    }).map(token => {
this map should be in a separate function and called here.

2017-10-17 08:35 UTC, zzacharo commented
@harunurhan check it again!

2017-10-17 09:16 UTC, harunurhan reviewed
just some names, and a duplicate thing.

2017-10-17 09:16 UTC, harunurhan commented on src/app/app.module.ts
> +    AutocompleteInputComponent,
duplicate

2017-10-17 09:16 UTC, harunurhan commented on src/app/shared/interfaces/autocompletion-state.ts
> +export interface AutoCompletionState {
`ParsedAutocompleteInput` would be better

2017-10-17 09:16 UTC, harunurhan commented on src/app/shared/interfaces/autocompletion-state.ts
> +  queryPath: string;
`query`

2017-10-17 09:24 UTC, zzacharo commented
@harunurhan done. Check it!

2017-10-17 11:14 UTC, harunurhan approved these changes

2017-10-17 11:14 UTC, merged