implement result buttons and styling
inspirehep/ng2-multi-record-editor pull request #28
Opened 2017-10-18 12:00 UTC by Glignos

Signed-off-by: Glignos <glignos93@gmail.com>

2017-10-18 12:42 UTC, Glignos commented
@harunurhan can you check? :)

2017-10-18 13:51 UTC, harunurhan requested changes

2017-10-18 13:51 UTC, harunurhan commented on src/app/shared/services/user-actions.service.ts
> +  userActions: UserActions = { actions: [], conditions: [] };
`private` and  have `get`,  `addAction`, `addCondition` etc.

2017-10-18 13:51 UTC, harunurhan commented on src/styles.scss
> +
so many new lines man!

2017-10-18 13:51 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.html
> +  <div *ngIf="previewMode === true">
`=== true` is redundant

2017-10-18 13:51 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.html
> +        <div class="col-lg-2">
`col-lg` alone without `sm` or `md` strategy doesn't make so much sense.

2017-10-18 13:51 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.html
> +        <ng-template #notPreview>
`notPreview` may better be changed to `textView` or sth

2017-10-19 08:35 UTC, harunurhan commented
@Glignos squash into 1 commit, when it's ready

2017-10-19 11:08 UTC, merged