general fixes:
inspirehep/ng2-multi-record-editor pull request #43
Opened 2017-10-27 11:10 UTC by Glignos

* Fix pagination overflowing on results number
* Change filtering strategy

  Signed-off-by: Glignos <glignos93@gmail.com>

2017-10-27 12:57 UTC, harunurhan requested changes

2017-10-27 12:57 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +    this.checkedRecords.length === 0 ? this.checkedRecords = this.uuids.slice() : this.checkedRecords = [];
use checkbox value instead of checking, maybe use `(ngValueChange)`

2017-10-27 12:57 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +  filterRecord(record: object , objectToAssign: object): object {
second param leftover.

2017-10-27 12:57 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
>      let _record = Object.assign({}, record);
unnecesarry

2017-10-27 12:57 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +      objectToAssign = filtered;
leftover

2017-10-27 12:57 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +    objectToAssign = record;
leftover

2017-10-27 12:57 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +      let filtered = this.jsonUtilsService.filterObject(_record, [this.filterExpression]);
`return this.jsonUtils...`

2017-10-27 12:57 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +    this.previewMode = false;
do this before where you call this function, also for readability reasons, put callee function right after the caller function.

2017-10-27 12:57 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
>    private queryCollection(query, collection) {
types!

2017-10-27 12:57 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +          this.changeDetectorRef.markForCheck();
outside the `if` because you are updating `errorMessage` either way.

2017-10-27 12:57 UTC, harunurhan commented on src/app/actions/actions.component.html
> +    <!--<option value="Addition">Addition</option> -->
WTF

2017-10-27 14:03 UTC, harunurhan commented on src/app/multi-editor/multi-editor.component.ts
> +    value ? this.checkedRecords = [] : this.checkedRecords = this.uuids.slice();
separate.

2017-10-27 14:03 UTC, harunurhan commented on src/app/shared/services/query.service.ts
> +  constructor(private http: Http) {}
```
public prop1;
private prop2;

constructor() {

}

method1() {

}

method2() {

}
```

2017-10-30 08:44 UTC, Glignos commented
@harunurhan  merge and release?

2017-10-30 09:26 UTC, merged